### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by beloso** [NSElvis/ANDYCardStack#1]
Have you got this to scroll up and down when there are more cards than fit the screen?

**Comment by a10k** [comment]
I was so excited about this repo.. it is awesome.. but, wish it came with the 
~ The Scrolling feature!
~ Snap back to initial position without opening when we try to put back a half pulled card..

**Comment by 3lvis** [comment]
Interesting! I'll have a look :)

**Comment by a10k** [comment]
I guess the snap back to initial position part will be irrelevant once the scrolling feature is implemented, right?

**Comment by 3lvis** [comment]
Hi guys! I figured out what's needed for this to work. The first thing is changing the UICollectionView's contentSize then disabling the cell panning so the gestures don't collide.

**Comment by GeetCD** [comment]
Hi, 
  I set the contentSize according to the number of items, but when a card is selected and the collection view is scrolled or bounced it messes up the entire stack array, and the cards layout gets all messed up, such as the screenshot attached
![img_0718](https://cloud.githubusercontent.com/assets/13621652/9811704/61e62774-5896-11e5-9d5a-cf097f3e2479.jpg)
![img_0719](https://cloud.githubusercontent.com/assets/13621652/9811702/61e090ac-5896-11e5-8e86-e52df89c7200.jpg)
![img_0721](https://cloud.githubusercontent.com/assets/13621652/9811703/61e39cca-5896-11e5-912c-c621f7d2e187.jpg)

**Comment by ingeniousgenius** [comment]
Any update on this?

**Comment by 3lvis** [comment]
Hi, there are already other pods that do better job than this one. Check out https://github.com/MillmanY/MMCardView for example.
