### ISSUE TITLE
Remove a Card from the View

### ISSUE THREAD

**Issue by GeetCD** [NSElvis/ANDYCardStack#2]
Hi, 

I have been using this repo for a while its serves my purpose quite efficiently, but have run into one issue, I cant seem to remove a card on the click of a button contained in it.

I removed the entry from my container array but the collection view dosen't seems to reload

the "[self.collectionView reload]" method is unavailable

Kindly help, I need to figure out how I can delete an entry from the view, without causing any issues to the user expierience

**Comment by 3lvis** [comment]
Hi! I'll take a look to see how this could be done. :)

**Comment by GeetCD** [comment]
Also, If the number of cards i higher, then after the cards which appears on screen there is no way to access the cards lying on the bottom since the collectionView wont scroll, can you kindly help on this.

**Comment by 3lvis** [comment]
@GeetCD the scrolling issue is been tracked down in #1

**Comment by 3lvis** [comment]
Hi, there are already other pods that do better job than this one. Check out https://github.com/MillmanY/MMCardView for example.
