### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [NSElvis/ANDYCardStack#5]
Hi,
For iOS and OS X projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods](http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/)

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by 3lvis** [comment]
What's up with all the spam? Could you STOP doing that?

<img width="369" alt="screen shot 2016-07-17 at 1 48 11 am" src="https://cloud.githubusercontent.com/assets/1088217/16897873/958c508a-4bc0-11e6-8409-f00a66fc1b5b.png">
